# Generated by Django 5.2.11 on 2026-02-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_usersession_remove_question_constraints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='function_signature',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='QuestionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.usersession')),
            ],
        ),
    ]
