# Generated by Django 5.2.11 on 2026-02-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_question_function_signature_questionsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='function_signature',
        ),
        migrations.AddField(
            model_name='question',
            name='function_templates',
            field=models.JSONField(default=dict),
        ),
    ]
